voyager_tls_broker_secret_name: "{{ vars | json_query('broker.tls_secret') | default(None, true) }}"
# TODO: Currently LE does not provide any alternative - still, we might want to adopt better semantics in 0.11
voyager_letsencrypt_challenge: "{{ 'dns' if 'dns' in (vars | json_query('letsencrypt.challenge_provider')) else 'http' }}"

voyager_broker_ingress_config:
  type: "{{ vars | json_query('broker.type') | default('LoadBalancer', true) }}"
  load_balancer_ip: "{{ vars | json_query('broker.load_balancer_ip') | default(None, true) }}"
  replicas: "{{ vars | json_query('broker.replicas') | default(1, true) }}"
  node_selector: "{{ vars | json_query('broker.node_selector') | default(None, true) }}"
  annotations_service: "{{ vars | json_query('broker.annotations_service') | default(None, true) }}"
  max_connections: "{{ vars | json_query('broker.max_connections') | default(10000, true) }}"
