apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: manager-webhook  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: system
spec:
  secretName: '{{ .Release.Name }}-webhook-server-cert'
