
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-api-astarte-platform-org-v1alpha1-astarte
  failurePolicy: Fail
  name: mastarte.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartes
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-api-astarte-platform-org-v1alpha1-astartevoyageringress
  failurePolicy: Fail
  name: mastartevoyageringress.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartevoyageringresses
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-api-astarte-platform-org-v1alpha1-flow
  failurePolicy: Fail
  name: mflow.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flows
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ingress-astarte-platform-org-v1alpha1-astartedefaultingress
  failurePolicy: Fail
  name: mastartedefaultingress.kb.io
  rules:
  - apiGroups:
    - ingress.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartedefaultingresses
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-api-astarte-platform-org-v1alpha1-astarte
  failurePolicy: Fail
  name: vastarte.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartes
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-api-astarte-platform-org-v1alpha1-astartevoyageringress
  failurePolicy: Fail
  name: vastartevoyageringress.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartevoyageringresses
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-api-astarte-platform-org-v1alpha1-flow
  failurePolicy: Fail
  name: vflow.kb.io
  rules:
  - apiGroups:
    - api.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flows
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ingress-astarte-platform-org-v1alpha1-astartedefaultingress
  failurePolicy: Fail
  name: vastartedefaultingress.kb.io
  rules:
  - apiGroups:
    - ingress.astarte-platform.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - astartedefaultingresses
  sideEffects: None
