- name: Generating RSA Housekeeping private key
  openssl_privatekey:
    path: /tmp/astarte_housekeeping.key
    size: 4096
    type: RSA
    force: yes

- name: Generating RSA Housekeeping public key
  openssl_publickey:
    path: /tmp/astarte_housekeeping.pub
    privatekey_path: /tmp/astarte_housekeeping.key
    format: PEM
    force: yes

- name: Store Housekeeping private key in dedicated K8S secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'housekeeping-private-key.yml') }}"
  ignore_errors: yes
  register: housekeeping_private_key_installed

- name: Ensure Housekeeping public key from generated file
  k8s:
    state: present
    definition: "{{ lookup('template', 'housekeeping-public-key.yml') }}"

- name: Delete RSA Housekeeping private key
  openssl_privatekey:
    path: /tmp/astarte_housekeeping.key
    state: absent

- name: Delete RSA Housekeeping public key
  openssl_publickey:
    path: /tmp/astarte_housekeeping.pub
    state: absent
