apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: {{ resources_computed_prefix }}broker-ingress-certificate
  namespace: {{ astarte_k8s_namespace }}
spec:
  domains:
    - {{ mqtt_broker_host }}
  acmeUserSecretName: {{ resources_computed_prefix }}voyager-acme-account
  challengeProvider:
    http:
      ingress:
        apiVersion: voyager.appscode.com/v1beta1
        kind: Ingress
        name: {{ resources_computed_prefix }}vernemq-ingress
