# permissions for end users to edit astartes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astarte-editor-role
rules:
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartes/status
  verbs:
  - get
