# permissions for end users to view astartedefaultingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astartedefaultingress-viewer-role
rules:
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartedefaultingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.astarte-platform.org
  resources:
  - astartedefaultingresses/status
  verbs:
  - get
