# permissions for end users to view astartevoyageringresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astartevoyageringress-viewer-role
rules:
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartevoyageringresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.astarte-platform.org
  resources:
  - astartevoyageringresses/status
  verbs:
  - get
