# permissions for end users to edit flows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flow-editor-role
rules:
- apiGroups:
  - api.astarte-platform.org
  resources:
  - flows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.astarte-platform.org
  resources:
  - flows/status
  verbs:
  - get
