apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: {{ resources_computed_prefix }}vernemq-ingress
  namespace: {{ astarte_k8s_namespace }}
  annotations:
    ingress.appscode.com/type: {{ voyager_broker_ingress_config.type }}
{% if voyager_broker_ingress_config.load_balancer_ip %}
    ingress.appscode.com/load-balancer-ip: '{{ voyager_broker_ingress_config.load_balancer_ip }}'
{% endif %}
    # Configure depending on the load
    ingress.appscode.com/replicas: '{{ voyager_broker_ingress_config.replicas }}'
{% if voyager_broker_ingress_config.node_selector %}
    ingress.appscode.com/node-selector: '{{ voyager_broker_ingress_config.node_selector }}'
{% endif %}
    # Keep source IP - we need this for a number of reasons
    ingress.appscode.com/keep-source-ip: "true"
    # These options are here to please VerneMQ/Astarte
    ingress.appscode.com/auth-tls-secret: {{ mqtt_broker_ca_secret }}
    ingress.appscode.com/auth-tls-verify-client: required
    # This is soft-capped to prevent Astarte from freaking out
    ingress.appscode.com/max-connections: "{{ voyager_broker_ingress_config.max_connections }}"
    # Meaningful options
    ingress.appscode.com/default-option: '{"tcplog": "true", "dontlognull": "true", "clitcpka": "true"}'
    # Configure these timeouts according to how frequently your client sends a PINGREQ - 1h is more than enough
    ingress.appscode.com/default-timeout: '{"connect": "30s", "server": "1h", "client": "1h", "tunnel": "1h"}'
spec:
  tls:
  - hosts:
    - {{ mqtt_broker_host }}
    ref:
{% if voyager_use_letsencrypt %}
      kind: Certificate
{% if voyager_letsencrypt_challenge == 'dns' %}
      name: {{ resources_computed_prefix }}ingress-certificate
{% else %}
      name: {{ resources_computed_prefix }}broker-ingress-certificate
{% endif %}
{% else %}
      kind: Secret
      name: {{ voyager_tls_broker_secret_name }}
{% endif %}
  rules:
  - host: {{ mqtt_broker_host }}
    tcp:
      port: '{{ mqtt_broker_port }}'
      backend:
        serviceName: {{ parent_resources_computed_prefix }}vernemq
        servicePort: '1885'
        backendRule:
        - 'balance source'
{% if voyager_letsencrypt_challenge == 'http' %}
# If we're using the http-01 challenge, we need to let the LoadBalancer know that port 80 has to be open and routed. We'll expose pairing here.
  - host: {{ mqtt_broker_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ parent_resources_computed_prefix }}pairing
          servicePort: '4000'
{% endif %}
