apiVersion: api.astarte-platform.org/v1alpha2
kind: Flow
metadata:
  name: example-flow
  namespace: astarte
spec:
  astarte:
    name: astarte
  astarteRealm: example-realm
  blocks:
    - id: example-realm-example-flow1
      image: your/flow_image:latest
      config: '{}'
      workers:
        - dataProvider:
            rabbitmq:
              exchange:
                name: ""
                routingKey: example-realm-example-flow1-inbound
              queues:
                - example-realm-example-flow1-outbound
          id: worker-0
  nativeBlocks: 2
  nativeBlocksResources:
    cpu: 10m
    memory: 2M
