# Adds namespace to all resources.
namespace: "{{ .Release.Namespace }}"
namePrefix: "{{ .Release.Name }}-"

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
- ../rbac
