- name: Ensure Voyager ACME Credentials
  k8s:
    state: present
    definition: "{{ lookup('template', 'voyager-acme-account.yml') }}"

- name: Ensure Voyager Let's Encrypt Certificate
  k8s:
    state: present
    definition: "{{ lookup('template', 'voyager-certificate.yml') }}"
  when:
    - voyager_letsencrypt_challenge == 'dns' or avi_ingresses_ready
