# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/api.astarte-platform.org_astartes.yaml
- bases/api.astarte-platform.org_astartevoyageringresses.yaml
- bases/api.astarte-platform.org_flows.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_astartes.yaml
- patches/webhook_in_astartevoyageringresses.yaml
- patches/webhook_in_flows.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

- patches/cainjection_in_astartes.yaml
- patches/cainjection_in_astartevoyageringresses.yaml
- patches/cainjection_in_flows.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
