name: Docs generation

on:
  push:
    paths:
    # Documentation
    - 'docs/**'
    # APIs
    - 'apis/**'
    # The workflow itself
    - '.github/workflows/generate-docs.yaml'
    branches:
    # Create the snapshot only when it matters
    - 'master'
    - 'release-*'
  # Run on branch/tag creation
  create:

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
    # Checkout the source
    - uses: actions/checkout@v2
      with:
        path: astarte-kubernetes-operator
    # Checkout the docs repository
    - uses: actions/checkout@v2
      with:
        repository: astarte-platform/docs
        ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
        path: docs
    # Setup Go for crd-ref-docs (ubuntu-20.04 defaults to go 1.15)
    # see https://github.com/actions/virtual-environments/issues/2447
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'
    # Generate CRD docs directory for Hugo
    - run: mkdir docs/content
      working-directory: astarte-kubernetes-operator
    # Generate CRD docs
    - run: make crd-docs
      working-directory: astarte-kubernetes-operator
    # Install Hugo
    - run: |
        curl -Lo hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.95.0/hugo_extended_0.95.0_Linux-64bit.tar.gz
        tar -zxvf hugo.tar.gz hugo
      working-directory: astarte-kubernetes-operator
    # Checkout the hugo-book theme
    - name: Checkout hugo-book
      uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: alex-shpak/hugo-book
        path: themes/hugo-book
    - name: Set docs dirname
      run: |
        DOCS_DIRNAME="$(echo ${{ github.ref }} | sed 's,refs/heads/,,' | sed 's/master/snapshot/g' | sed 's/release-//g')/astarte-kubernetes-operator"
        echo "DOCS_DIRNAME=$DOCS_DIRNAME" >> $GITHUB_ENV
    - name: Apply docs dirname to Hugo config
      run: |
          echo "baseURL: https://docs.astarte-platform.org/$DOCS_DIRNAME" >> docs/hugo/config.yaml
      working-directory: astarte-kubernetes-operator
    # Run hugo to build docs page
    - name: Build docs
      run: ./hugo --config docs/hugo/config.yaml --contentDir docs/content --themesDir ../themes --destination docs/generated --verbose --verboseLog
      working-directory: astarte-kubernetes-operator
    - name: Copy Docs
      run: |
        rm -rf docs/$DOCS_DIRNAME
        mkdir -p docs/$DOCS_DIRNAME
        cp -r astarte-kubernetes-operator/docs/generated/* docs/$DOCS_DIRNAME/
    - name: Commit files
      working-directory: ./docs
      run: |
        git config --local user.email "astarte-machine@ispirata.com"
        git config --local user.name "Astarte Bot"
        git add .
        git commit -m "Update Astarte Kubernetes Operator documentation"
    - name: Push changes
      working-directory: ./docs
      run: |
        git push origin master
