#
# This file is part of Astarte.
#
# Copyright 2020 Ispirata Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "Operator e2e tests"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        testSuite:
        - "011"
        - "10"
        kubernetesNodeImage:
        - "kindest/node:v1.22.15@sha256:7d9708c4b0873f0fe2e171e2b1b7f45ae89482617778c1c875f1053d4cef2e41"
        - "kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61"
        - "kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315"
        - "kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1"
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        # Ensure we're on Go 1.18
        go-version: '1.18.x'
    - uses: stefanprodan/kube-tools@v1.5.0
      with:
        kubectl: 1.22.0
        kustomize: 3.8.7
        helm: 2.16.7
        helmv3: 3.8.0
    - name: Set nf_conntrack_max value
      # This step is required to avoid CrashLoopBackOff for kube-proxy
      # see https://github.com/kubernetes-sigs/kind/issues/2240#issuecomment-838510890
      run: |
        sudo sysctl net/netfilter/nf_conntrack_max=131072
    - uses: container-tools/kind-action@v2
      with:
        version: "v0.17.0"
        node_image: "${{ matrix.kubernetesNodeImage }}"
    - name: Ensure KinD is up
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    - name: Dump cluster info
      run: |
        kubectl cluster-info dump
    - name: Setup needed resources
      run: |
        kubectl create namespace astarte-test
        make install
    - name: Run e2e tests
      run: go test -v -timeout 20m ./...
      working-directory: "test/e2e${{ matrix.testSuite }}"
      env:
        USE_EXISTING_CLUSTER: "true"
    - name: Dump debug info
      if: failure()
      run: |
        kubectl get pods -n astarte-test
        kubectl get deployment -n astarte-test
        kubectl get statefulset -n astarte-test
        kubectl get secrets -n astarte-test
        kubectl get configmaps -n astarte-test
        kubectl get pvc -n astarte-test
        kubectl describe astarte -n astarte-test || echo "Astarte already deleted"
        kubectl logs -n astarte-test deployment/example-astarte-flow || echo "No logs"
        kubectl logs -n astarte-test deployment/example-astarte-flow --previous || echo "No logs"
    - name: Show pod states
      run: |
        kubectl get pods -n astarte-test
